// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjolbqhdnyrktxnugixe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqb2xicWhkbnlya3R4bnVnaXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDkwNTAsImV4cCI6MjA2OTk4NTA1MH0.-RVZ0b3Ia885rbzrszkPb2JpR4654A_xssNSUow4Y8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});